### ISSUE TITLE
Add link to original document

### ISSUE THREAD

**Issue by mihaeu** [mihaeu/cosmere#13]
# Problem

Add a way to specify a link to the original document in the prefix.

E.g. 

```json
{
  "prefix": "This document is automatically generated. Please don't edit it directly! ${originalDocument}"
}
```

**Comment by mihaeu** [comment]
This is already possible with normal markup, I don't think there needs to be a feature for this very specific case.

**Comment by hudrid** [comment]
Hello, @mihaeu! 

Tell me, please, is there now an opportunity to add a link to the `prefix` parameter so that it appears as a link in Confluence?

**Comment by mihaeu** [comment]
Hi, just use a normal HTML link. It's supported by Confluence e.g. <a href="
https://example.com">Link</a>

**Comment by hudrid** [comment]
```json
"prefix": "Some text. Please, look at the <a href='https://example.com'>Link</a>.",
```
It works. Thanx :)
