### ISSUE TITLE
Horizontal lines not supported?

### ISSUE THREAD

**Issue by LMarsoner** [mihaeu/cosmere#14]
The following markdown caused a `Error: Request failed with status code 400` when trying to sync to Confluence:

`---`

Thank you very much for creating this very nice project and have a lovely day
Lukas

**Comment by mihaeu** [comment]
Thanks for the report @LMarsoner :)

Turns out I simply needed to write self-closing tags in XHTML, not HTML 5 style. I wanna fix one or two things more and will then release a tag.

**Comment by LMarsoner** [comment]
Thank you very much! :)

Have a lovely rest of the week
