### ISSUE TITLE
Add support for Atlassian access tokens

### ISSUE THREAD

**Issue by codethief** [mihaeu/cosmere#26]
Instead of sending username / password, I would like be able to send an `Authorization: Bearer <my token>` HTTP header to `https://<confluence url>/rest/api` as basic HTTP auth is getting disabled in more and more Confluence setups these days.

**Comment by mihaeu** [comment]
Hey @codethief, thanks for the idea. Makes a lot of sense. This weekend will be rainy over here, so I'll probably get around to doing it then :grinning:

**Comment by mihaeu** [comment]
I was thinking about adding an auth flag like `--bearer-auth=<TOKEN>`: 

```
Usage:
  cosmere [--force] [--config=<path>] [--bearer-auth=<TOKEN>]
  cosmere generate-config [--config=<path>]

Options:
  --force           always upload even if the file looks the same
  --config=<path>   specify the path to the config
```

What do you think?

**Comment by codethief** [comment]
How about just adding another setting to the config? That way, it would be more consistent with the existing setup. :)

**Comment by codethief** [comment]
@mihaeu Any update on this? If not, I would give this a shot and send in a patch. :)

**Comment by mihaeu** [comment]
That would be very welcome 🤗

**Comment by codethief** [comment]
There you go: https://github.com/mihaeu/cosmere/pull/29 :)

**Comment by mihaeu** [comment]
Thanks :wave: it's been a long week, but I'll try to get it merged in this weekend.

**Comment by mihaeu** [comment]
Finally merged :)
