### ISSUE TITLE
Axios error in 0.17.0

### ISSUE THREAD

**Issue by rion18** [mihaeu/cosmere#37]
It seems that the 0.17.0 version is not uploading attachments to Confluence. Maybe we can revert the change introduced in

https://github.com/mihaeu/cosmere/commit/eee00c6dfd16dbef0729af703de1ee336dc3149e
https://github.com/mihaeu/cosmere/commit/368380ee92d9892c90a54a788a2b49d4ab111874

where, instead of deleting the files at the end of the process, it was changed to delete the file PER attachment call

**Comment by rion18** [comment]
Please ignore... Something happened on my local env

**Comment by rion18** [comment]
I can confirm that using cosmere 0.16.0 using [patch-package](https://www.npmjs.com/package/patch-package) with the contents of my original PR works. I can do some tests on my end (like deleting the attachments first instead of at the end) to see what's up. Maybe I can see what's up next week.

**Comment by mihaeu** [comment]
Hi @rion18 I'm surprised because I've been using it and I'm pretty sure also without cache, but I'll double check later today. It'd be nice to have a staging instance of Confluence, maybe I'll see if I can get a free cloud account.

**Comment by mihaeu** [comment]
The problem was the upgrade of marked from 0.x to 4.x

Escaping behaviour changed. I guess it was a bit ambitious of us to do all this in one PR. But at least we're up to date now. In 0.17.2 things work as expected.

Now I just need a test instance for integration tests and bring code coverage to 100% and then I'll release 1.0.0

**Comment by rion18** [comment]
Oh my... I'm so sorry about that! I saw that there were some tests regarding the output so I thought the migration to marked 4.x worked. I was wrong though :(.  You can count on me if you need help with some of the tests. So glad that 0.17.2 has that new behavior corrected.
